import React, { Component } from 'react'

export default class AboutPage extends Component {
  render() {
    return (
      <div>
        <h1>About Page</h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam, accusantium! Dolorem quibusdam temporibus nihil corporis aliquam. Doloremque magni doloribus sit, voluptas facere beatae quidem numquam reprehenderit itaque excepturi delectus assumenda. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam recusandae placeat officia esse aspernatur commodi doloremque! Ex nihil hic ipsam asperiores aspernatur dolore quod, neque nisi provident esse dolores iusto?</p>
      </div>
    )
  }
}
